name: Nathaniel Zeisler
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18428
title: 'My Photo Journal '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151930'
    - '#a5c3e0'
    - '#5e76b1'
    - '#f8f5d6'
    - '#c17b6e'
  brandStrength: 0.25
  lightness: 0.2525931606069207
  saturation: 0.030166415264829993
  rhythmicContrast: 0.6986392335966229
purpose: []
